[theme]
primaryColor="#00FF41"
backgroundColor="#0D0208"
secondaryBackgroundColor="#001a00"
textColor="#00FF41"
font="monospace"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
